Update .github/workflows/build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,6 +1,8 @@
 name: Build API Specification
 
 on:
+  schedule:
+    - cron: '*/5 * * * *'
   workflow_dispatch:
 
 jobs:
@@ -8,68 +10,63 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout main repository office-js-api
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.10'
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+
+      - name: Checkout repository office-js-api
         uses: actions/checkout@v4
         with:
+          ref: master
           path: office-js-api
 
       - name: Checkout build_tools repository
         uses: actions/checkout@v4
         with:
           repository: ONLYOFFICE/build_tools
-          ref: release/v8.2.0
+          token: ${{ secrets.READ_PAT }}
+          ref: master
           path: build_tools
+
+      - name: Check release/hotfix branch for build
+        run: |
+          cd build_tools/scripts/sdkjs_common/jsdoc
+          branch=$(python get_latest_branch.py)
+          echo "Branch for build: $branch"
+          echo "build_branch=$branch" >> $GITHUB_ENV
 
       - name: Checkout sdkjs repository
         uses: actions/checkout@v4
         with:
           repository: ONLYOFFICE/sdkjs
-          ref: release/v8.2.0
+          token: ${{ secrets.READ_PAT }}
+          ref: ${{ env.build_branch }}
           path: sdkjs
 
       - name: Checkout sdkjs-forms repository
         uses: actions/checkout@v4
         with:
           repository: ONLYOFFICE/sdkjs-forms
-          ref: release/v8.2.0
+          token: ${{ secrets.READ_PAT }}
+          ref: ${{ env.build_branch }}
           path: sdkjs-forms
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-
-      - name: Install Node.js dependencies
+      - name: Generate docs
         run: |
+          git -C build_tools switch "$build_branch" || echo "Failed to switch $build_branch in build_tools"
           cd build_tools/scripts/sdkjs_common/jsdoc
           npm install
+          python generate_docs_md.py
+          cd ../../../../office-js-api
 
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.10'
-
-      - name: Run Python script to generate docs
-        run: |
-          cd build_tools/scripts/sdkjs_common/jsdoc
-          output=$(python generate_docs_md.py)
-          missing_examples=$(echo "$output" | sed -n '/START_MISSING_EXAMPLES/,/END_MISSING_EXAMPLES/p' | sed '1d;$d')
-          echo "missing_examples=$missing_examples" >> $GITHUB_ENV
-
-      - name: Set up Git
-        run: |
-          git config --global user.name "github-actions[bot]"
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-
-      - name: Create Pull Request
-        run: |
-          BRANCH_NAME="update-api-spec-${{ github.run_number }}"
-          cd office-js-api
-          git checkout -b $BRANCH_NAME
-          git add .
-          git commit -m "Add documentation update from GitHub Actions"
-          git push origin $BRANCH_NAME
-          url_prefix="../blob/$BRANCH_NAME/"
-          formatted_examples=$(echo "${{ env.missing_examples }}" | tr ',' '\n' | awk -v prefix="$url_prefix" '{print "[" $0 "](" prefix $0 ")"}')
-          body_message=$'This PR includes updates to the documentation artifacts generated by the GitHub Actions workflow. Here is a list of missing examples:\n'"$formatted_examples"
-          gh pr create --title "Update documentation from GitHub Actions" --body "$body_message" --base master --head $BRANCH_NAME
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          if ! git diff --exit-code; then
+            git add .
+            git commit -m "Add documentation update from GitHub Actions"
+            git push origin develop
+          else
+            echo "Nothing to commit"
+          fi
